version: '3.9'

services:
  db:
    image: postgres:12.12
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go-backend
    ports:
      - "5432:5432"
    volumes:
      - ./_db:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
      
 # - "postgresql://postgres:password@localhost:5432/go-backend?sslmode=disable"
