version: '3.9'

services:
  db:
    image: postgres:12.12
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go-backend
    ports:
      - "5432:5432"
    volumes:
      - ./_db:/var/lib/postgresql/data
  app:
    image: sing3demons/gin-backend-apt:0.1
    build: .
    container_name: go-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - DATABASE_DSN=postgresql://postgres:password@db:5432/go-backend?sslmode=disable&TimeZone=Asia/Bangkok
      - JWT_SECRET=4614A26F-273E-4FB1-B282-4B64AE60591D
    depends_on:
      - db
